#!/usr/bin/env python3
"""Read, write and audit the kerning table inside kawara2.glyphs.

The .glyphs file is a NeXTSTEP-style plist. This module edits only the
top-level `kerning = {...};` block as text, so the rest of the file stays
byte-for-byte identical (nice for git diffs).

CLI:
    python3 tools/kawara_kerning.py export [-o www/kerning.js]
    python3 tools/kawara_kerning.py apply kerning.json
    python3 tools/kawara_kerning.py audit
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GLYPHS_FILE = REPO / "kawara2.glyphs"

UPPER = set("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
LOWER = set("abcdefghijklmnopqrstuvwxyz")

# character shown in the workbench for each glyph name
GLYPH_TO_CHAR = {
    **{c: c for c in UPPER | LOWER},
    "zero": "0", "one": "1", "two": "2", "three": "3", "four": "4",
    "five": "5", "six": "6", "seven": "7", "eight": "8", "nine": "9",
    "comma": ",", "period": ".", "quotesingle": "'", "hyphen": "-",
    "space": " ",
}


def find_kerning_block(text):
    """Return (start, end) offsets of the top-level kerning block,
    from 'kerning = {' up to and including its closing '};\n'."""
    m = re.search(r"^kerning = \{$", text, re.M)
    if not m:
        raise ValueError("no `kerning = {` block found in " + str(GLYPHS_FILE))
    depth = 0
    i = m.start()
    while i < len(text):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                # consume the trailing ';' and newline
                j = i + 1
                while j < len(text) and text[j] in ";\n":
                    j += 1
                return m.start(), j
        i += 1
    raise ValueError("unbalanced braces in kerning block")


def read_kerning(path=GLYPHS_FILE):
    """Parse the kerning block. Returns (master_id, {left: {right: int}})."""
    text = path.read_text()
    start, end = find_kerning_block(text)
    block = text[start:end]
    master_m = re.search(r'^"([0-9A-F-]+)" = \{$', block, re.M)
    if not master_m:
        raise ValueError("no master id found in kerning block")
    master_id = master_m.group(1)

    kerning = {}
    left = None
    for line in block[master_m.end():].splitlines():
        line = line.strip()
        pair_m = re.match(r'^([A-Za-z]+) = \{$', line)
        val_m = re.match(r'^([A-Za-z]+) = "?(-?\d+)"?;$', line)
        if pair_m:
            left = pair_m.group(1)
            kerning[left] = {}
        elif val_m and left is not None:
            kerning[left][val_m.group(1)] = int(val_m.group(2))
        elif line == "};":
            left = None
    return master_id, kerning


def serialize_kerning(master_id, kerning):
    """Emit the kerning block in Glyphs' plist conventions
    (negative numbers quoted, keys sorted for stable diffs)."""
    out = ["kerning = {", f'"{master_id}" = {{']
    for left in sorted(k for k, v in kerning.items() if v):
        out.append(f"{left} = {{")
        for right in sorted(kerning[left]):
            v = int(kerning[left][right])
            val = f'"{v}"' if v < 0 else str(v)
            out.append(f"{right} = {val};")
        out.append("};")
    out.append("};")
    out.append("};")
    return "\n".join(out) + "\n"


def write_kerning(kerning, path=GLYPHS_FILE):
    """Replace the kerning block in the .glyphs file, leaving all other
    bytes untouched. Returns the number of pairs written."""
    text = path.read_text()
    start, end = find_kerning_block(text)
    master_id, _ = read_kerning(path)
    clean = {l: {r: int(v) for r, v in rs.items()} for l, rs in kerning.items() if rs}
    path.write_text(text[:start] + serialize_kerning(master_id, clean) + text[end:])
    return sum(len(rs) for rs in clean.values())


def glyph_widths():
    """Glyph advance widths from the source, for the workbench."""
    import glyphsLib
    font = glyphsLib.GSFont(str(GLYPHS_FILE))
    return {g.name: int(g.layers[0].width) for g in font.glyphs}


def export_js(out_path):
    master_id, kerning = read_kerning()
    data = {
        "familyName": "On Kawara",
        "upm": 1000,
        "masterId": master_id,
        "glyphToChar": GLYPH_TO_CHAR,
        "widths": glyph_widths(),
        "kerning": kerning,
    }
    out_path.write_text(
        "// generated by tools/kawara_kerning.py export — do not edit by hand\n"
        "window.KAWARA = " + json.dumps(data, indent=1, sort_keys=True) + ";\n"
    )
    pairs = sum(len(v) for v in kerning.values())
    print(f"exported {pairs} pairs -> {out_path}")


def apply_json(json_path):
    raw = json.loads(Path(json_path).read_text())
    kerning = raw.get("kerning", raw)  # accept wrapped or flat
    known = set(glyph_widths())
    bad = [g for g in kerning for r in ((g,) + tuple(kerning[g])) if r not in known]
    if bad:
        sys.exit(f"unknown glyph names in {json_path}: {sorted(set(bad))}")
    _, before = read_kerning()
    n = write_kerning(kerning)
    added = sum(1 for l in kerning for r in kerning[l] if r not in before.get(l, {}))
    removed = sum(1 for l in before for r in before[l] if r not in kerning.get(l, {}))
    changed = sum(1 for l in kerning for r in kerning[l]
                  if r in before.get(l, {}) and before[l][r] != int(kerning[l][r]))
    print(f"wrote {n} pairs to {GLYPHS_FILE.name} "
          f"(+{added} new, ~{changed} changed, -{removed} removed)")
    print("run `make build` to bake them into the OTF")


def audit():
    """Report case inconsistencies. Lowercase glyphs are components of the
    uppercase ones, so all four case combinations of a letter pair should
    normally share one value."""
    _, kerning = read_kerning()

    def get(l, r):
        return kerning.get(l, {}).get(r)

    rows = []
    for L in sorted(UPPER):
        for R in sorted(UPPER):
            combos = {
                f"{L}/{R}": get(L, R),
                f"{L}/{R.lower()}": get(L, R.lower()),
                f"{L.lower()}/{R}": get(L.lower(), R),
                f"{L.lower()}/{R.lower()}": get(L.lower(), R.lower()),
            }
            values = {v for v in combos.values() if v is not None}
            defined = {k: v for k, v in combos.items() if v is not None}
            if len(values) > 1:
                rows.append(("MIXED", combos))
            elif values and len(defined) < 4:
                rows.append(("PARTIAL", combos))
    mixed = [r for r in rows if r[0] == "MIXED"]
    partial = [r for r in rows if r[0] == "PARTIAL"]
    print(f"{len(mixed)} letter pairs with conflicting case values:")
    for _, combos in mixed:
        print("  " + "  ".join(f"{k}={v if v is not None else '—'}" for k, v in combos.items()))
    print(f"\n{len(partial)} letter pairs defined for some case combinations only:")
    for _, combos in partial:
        pairs = "  ".join(f"{k}={v}" for k, v in combos.items() if v is not None)
        missing = ",".join(k for k, v in combos.items() if v is None)
        print(f"  {pairs}   (missing {missing})")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p_exp = sub.add_parser("export", help="write kerning data to www/kerning.js")
    p_exp.add_argument("-o", "--out", default=str(REPO / "www" / "kerning.js"))
    p_app = sub.add_parser("apply", help="apply a kerning JSON (workbench export) to the .glyphs source")
    p_app.add_argument("json_file")
    sub.add_parser("audit", help="report case-inconsistent letter pairs")
    args = ap.parse_args()
    if args.cmd == "export":
        export_js(Path(args.out))
    elif args.cmd == "apply":
        apply_json(args.json_file)
    elif args.cmd == "audit":
        audit()


if __name__ == "__main__":
    main()
